/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[7] = {1, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s1[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s2[6] = {1, 2, 0, 1, 1, 0};
static const casadi_int casadi_s3[3] = {0, 1, 3};
static const casadi_int casadi_s4[6] = {1, 2, 0, 0, 1, 0};
static const casadi_int casadi_s5[11] = {3, 3, 0, 1, 3, 5, 0, 1, 2, 1, 2};
static const casadi_int casadi_s6[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s10[6] = {0, 3, 0, 0, 0, 0};

static const casadi_real casadi_c0[4] = {2000., 0., 0., 2.0000000000000000e-02};

/* unbalanced_disc_fn_cost_ext_cost_fun_jac_hess:(i0[2],i1,i2[],i3[])->(o0,o1[3],o2[3x3,5nz],o3[],o4[0x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, *w2=w+4, *w3=w+6, *w4=w+8, w5, w6, w7, *w8=w+15, *w9=w+19, *w10=w+24, *w11=w+27;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 2, w2);
  /* #3: @3 = @2' */
  casadi_copy(w2, 2, w3);
  /* #4: @4 = 
  [[2000, 0], 
   [0, 0.02]] */
  casadi_copy(casadi_c0, 4, w4);
  /* #5: @1 = mac(@3,@4,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #6: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #7: @5 = 0.02 */
  w5 = 2.0000000000000000e-02;
  /* #8: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #9: @7 = (@5*@6) */
  w7  = (w5*w6);
  /* #10: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #11: @0 = (@0+@6) */
  w0 += w6;
  /* #12: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #13: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #14: output[1][0] = @7 */
  if (res[1]) res[1][0] = w7;
  /* #15: @1 = @1' */
  /* #16: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #17: @2 = @2' */
  /* #18: @8 = @4' */
  for (i=0, rr=w8, cs=w4; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #19: @3 = mac(@2,@8,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w8+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #20: @3 = @3' */
  /* #21: @1 = (@1+@3) */
  for (i=0, rr=w1, cs=w3; i<2; ++i) (*rr++) += (*cs++);
  /* #22: output[1][1] = @1 */
  if (res[1]) casadi_copy(w1, 2, res[1]+1);
  /* #23: @9 = zeros(3x3,5nz) */
  casadi_clear(w9, 5);
  /* #24: @1 = ones(3x1,2nz) */
  casadi_fill(w1, 2, 1.);
  /* #25: {@7, @0} = vertsplit(@1) */
  w7 = w1[0];
  w0 = w1[1];
  /* #26: @5 = (@5*@7) */
  w5 *= w7;
  /* #27: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #28: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #29: @7 = @0' */
  casadi_copy((&w0), 1, (&w7));
  /* #30: @1 = mac(@7,@4,@1) */
  casadi_mtimes((&w7), casadi_s2, w4, casadi_s1, w1, casadi_s0, w, 0);
  /* #31: @1 = @1' */
  /* #32: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #33: @0 = @0' */
  /* #34: @3 = mac(@0,@8,@3) */
  casadi_mtimes((&w0), casadi_s2, w8, casadi_s1, w3, casadi_s0, w, 0);
  /* #35: @3 = @3' */
  /* #36: @1 = (@1+@3) */
  for (i=0, rr=w1, cs=w3; i<2; ++i) (*rr++) += (*cs++);
  /* #37: @10 = vertcat(@5, @1) */
  rr=w10;
  *rr++ = w5;
  for (i=0, cs=w1; i<2; ++i) *rr++ = *cs++;
  /* #38: (@9[:3] = @10) */
  for (rr=w9+0, ss=w10; rr!=w9+3; rr+=1) *rr = *ss++;
  /* #39: (@9[0, 1, 3] = @10) */
  for (cii=casadi_s3, rr=w9, ss=w10; cii!=casadi_s3+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #40: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #41: @5 = ones(3x1,1nz) */
  w5 = 1.;
  /* #42: {NULL, @0} = vertsplit(@5) */
  w0 = w5;
  /* #43: @5 = @0' */
  casadi_copy((&w0), 1, (&w5));
  /* #44: @1 = mac(@5,@4,@1) */
  casadi_mtimes((&w5), casadi_s4, w4, casadi_s1, w1, casadi_s0, w, 0);
  /* #45: @1 = @1' */
  /* #46: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #47: @0 = @0' */
  /* #48: @3 = mac(@0,@8,@3) */
  casadi_mtimes((&w0), casadi_s4, w8, casadi_s1, w3, casadi_s0, w, 0);
  /* #49: @3 = @3' */
  /* #50: @1 = (@1+@3) */
  for (i=0, rr=w1, cs=w3; i<2; ++i) (*rr++) += (*cs++);
  /* #51: (@9[3:5] = @1) */
  for (rr=w9+3, ss=w1; rr!=w9+5; rr+=1) *rr = *ss++;
  /* #52: (@9[2:6:2] = @1) */
  for (rr=w9+2, ss=w1; rr!=w9+6; rr+=2) *rr = *ss++;
  /* #53: @11 = @9' */
  casadi_trans(w9,casadi_s5, w11, casadi_s5, iw);
  /* #54: output[2][0] = @11 */
  casadi_copy(w11, 5, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int unbalanced_disc_fn_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s9;
    case 2: return casadi_s5;
    case 3: return casadi_s8;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unbalanced_disc_fn_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 32;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
